name: cube_timer_oficial
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.1
  flutter_svg: ^2.2.1
  modal_bottom_sheet: ^3.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  sqlite3: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.28.3
  build_runner: ^2.7.1
  riverpod_lint: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/category/
    - assets/drawer_templates/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Bold.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.otf
        - asset: fonts/Poppins-Light.otf
        - asset: fonts/Poppins-SemiBold.otf
        - asset: fonts/Poppins-Bold.otf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand_Regular.ttf
        - asset: fonts/Quicksand_SemiBold.ttf
        - asset: fonts/Quicksand_Book.otf
        - asset: fonts/Quicksand_Light.otf
        - asset: fonts/Quicksand_Bold.ttf
        - asset: fonts/Quicksand_Medium.ttf
    - family: CubeIcon
      fonts:
        - asset: fonts/CubeIcon.ttf
