name: cube_timer_oficial
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.1
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  sqlite3: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.28.3
  build_runner: ^2.7.1
  riverpod_lint: ^3.0.1

flutter:
  uses-material-design: true
